env:
  TERM: xterm-256color

window:
  decorations: full
  padding:
    x: 5
    y: 5

font:
  normal:
    family: Source Code Pro
  bold:
    family: Source Code Pro
  italic:
    family: Source Code Pro
  size: 10
  # background_opacity: 0.85
colors:
  primary:
    background: '0x303030'
    foreground: '0xcccccc'
  normal:
    black:   '0x282828'
    red:     '0xea9090'
    green:   '0x90cfb0'
    yellow:  '0xf9d87a'
    blue:    '0x63b1bc'
    magenta: '0xd58cff'
    cyan:    '0x6acad8'
    white:   '0xdedede'
  bright:
    black:   '0x282828'
    red:     '0xea9090'
    green:   '0x90cfb0'
    yellow:  '0xf9d87a'
    blue:    '0x63b1bc'
    magenta: '0xd58cff'
    cyan:    '0x6acad8'
    white:   '0xdedede'
