WALLPAPERS_DIR="$HOME/Wallpapers"
test ! -d "$WALLPAPERS_DIR" && mkdir "$WALLPAPERS_DIR"
xdg-user-dirs-update --set WALLPAPERS "$WALLPAPERS_DIR"

typeset -U PATH path
path=(
    "$HOME/.local/bin"
    "$HOME/.local/share/npm/bin"
    "$path[@]"
)
export PATH

export XDG_CURRENT_DESKTOP=sway
export _JAVA_AWT_WM_NONREPARENTING=1
wmname LG3D

