autoload -U colors && colors

setopt autocd
stty stop undef

HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.cache/zsh/history

setopt INC_APPEND_HISTORY
setopt HIST_IGNORE_ALL_DUPS

autoload -U compinit
zstyle ':completion:*' menu select
zmodload zsh/complist
compinit
_comp_options+=(globdots)

PS1="%n@%M %~ > "

bindkey -v
export KEYTIMEOUT=1

bindkey -M menuselect "h" vi-backward-char
bindkey -M menuselect "j" vi-down-line-or-history
bindkey -M menuselect "k" vi-up-line-or-history
bindkey -M menuselect "l" vi-forward-char
bindkey -v "^?" backward-delete-char

function zle-keymap-select () {
    case $KEYMAP in
        vicmd) echo -ne "\e[1 q";;      # block
        viins|main) echo -ne "\e[5 q";; # beam
    esac
}
zle -N zle-keymap-select
zle-line-init() {
    zle -K viins
    echo -ne "\e[5 q"
}
zle -N zle-line-init
echo -ne "\e[5 q"
preexec() { echo -ne "\e[1 q" ;}

source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

export VISUAL="nvim"
export EDITOR="nvim"

alias ls="ls --color"
alias grep="grep --color"

